version: '3'
services:
  nginx:
    build:
      context: ./docker/nginx
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - ./:/src

  app:
    build:
      context: ./docker/php
    depends_on:
      - mysql
    ports:
      - 5173:5173
    volumes:
      - ./:/src
      - /src/node_modules
      - /src/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    command: bash -c "composer install; npm install; npm run dev & exec php-fpm;"

  mysql:
    image: mysql:8.0.28
    command: --max_allowed_packet=32505856
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=memo
    ports:
      - 3306:3306

  redis:
    image: redis:alpine
    ports:
      - 16379:6379